import Footer from "@/components/Footer";
import Loader from "@/components/Loader/Loader";
import Navbar from "@/components/Navbar";
import PageNav from "@/components/pageNavigation/PageNav";
import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "./productPage.module.scss";

const home = ({ query }) => {
  const { product_id } = query;
  const [loading, setLoading] = useState(false);
  const [state, setState] = useState({
    details: [],
  });

  console.log(product_id);

  useEffect(() => {
    fetchProduct();
  }, []);

  const fetchProduct = async () => {
    setLoading(true);
    try {
      const res = await axios.post("/api/fetchProduct", {
        product_id: product_id,
      });
      console.log(res);
      const data = res.data.data;
      setState(data);
    } catch (err) {
      console.log(err);
    }
    setLoading(false);
  };

  return (
    <>
      <Head>
        <title>Graphene Pro - Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo_sm.png" />
      </Head>
      <main className="main">
        <Navbar />
        <PageNav title={state.product_name} />
        {loading && <Loader />}
        <div className="pageContainer">
          <div className={styles.productPageContainer}>
            <div className={styles.ImageSection}>
              {
                <div className={styles.imageContainer}>
                  <img src={state.main_image_url} alt="" />
                </div>
              }
            </div>
            <div className={styles.InfoSection}>
              {state?.details?.map((d, idx) => {
                return (
                  <div className={styles.indiDetail}>
                    {d.type === "punchline" && (
                      <p className="title-hero2">{d.data}</p>
                    )}
                    {d.type === "heading" && (
                      <p className="subtitle mt-6">{d.data}</p>
                    )}
                    {d.type === "body" && <p className="body">{d.data}</p>}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
};

export default home;

export const getServerSideProps = async (context) => {
  const { query } = context;
  return { props: { query } };
};
