import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import PageNav from "@/components/pageNavigation/PageNav";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "@/styles/allProducts.module.scss";
import ProductCard from "@/components/card/ProductCard";
import axios from "axios";

const allProducts = () => {
  const [allProducts, setAllProducts] = useState([]);
  const [loading, setLoading] = useState(false);

  const fetchAllProducts = async () => {
    setLoading(true);
    try {
      const res = await axios.get("/api/allproducts");
      console.log(res);

      setAllProducts(res.data.data);
      toast.success(`Successfully fetched all products`);
    } catch (err) {
      console.log(err);
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchAllProducts();
  }, []);

  return (
    <>
      <Head>
        <title>Graphenera - All Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo_sm.png" />
      </Head>
      <main className="main">
        <Navbar />
        <PageNav title="All Products" />
        <div className={styles.section1}>
          <div className={styles.productList}>
            {allProducts.map((pr, index) => (
              <ProductCard data={pr} idx={index} client={true} />
            ))}
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
};

export default allProducts;
