import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import PageNav from "@/components/pageNavigation/PageNav";
import Head from "next/head";
import styles from "@/styles/dealers.module.scss";
import { useState } from "react";
import Map from "./Map";

const AnyReactComponent = ({ text }) => <div>{text}</div>;
const MAPS_API_KEY = process.env.GOOGLE_MAPS_API_KEY;

const home = () => {
  const [state, setState] = useState({
    center: {
      lat: 28.7041,
      lng: 77.1025,
    },
    zoom: 10,
    stores: [
      {
        lat: 28.7041,
        lng: 77.1088,
        address: "",
        city: "",
        state: "",
      },
    ],
  });

  return (
    <>
      <Head>
        <title>Graphene Pro - Dealer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo_sm.png" />
      </Head>
      <main className="main">
        <Navbar />
        <PageNav title="Dealers" />
        <div className={styles.dealers}>
          <div className={styles.dealersMap}>
            <div className={styles.dealerMapArea}>
              <Map
                containerStyle={{ width: "100%", height: "100%" }}
                state={state}
              />
            </div>
          </div>
          <div className={styles.dealerInfo}></div>
        </div>
        <Footer />
      </main>
    </>
  );
};

export default home;
