import Head from "next/head";
import { useRouter } from "next/router";
import { toast } from "react-toastify";
import { useEffect, useState } from "react";
import Loader from "@/components/Loader/Loader";
import { useAuth } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
import styles from "@/styles/login.module.scss";
import PrimaryButton from "@/components/buttons/PrimaryButton";
import TextInput from "@/components/inputs/TextInput";

export default function Home() {
  const router = useRouter();
  const { logIn, setUser } = useAuth();
  const [state, setState] = useState({
    email: "",
    password: "",
  });
  const [formErrors, setFormErrors] = useState({});
  const [isSubmit, setIsSubmit] = useState(false);
  const [loading, setLoading] = useState(false);

  const submitData = async (data) => {
    console.log(data);
    setLoading(true);
    try {
      const res = await logIn(data.email, data.password);
      router.push("/admin");
    } catch (error) {
      if (error.code === "auth/wrong-password") {
        toast.warning("Wrong Password");
      }
      if (error.code === "auth/user-not-found") {
        toast.warning("User  not found! Please create an account first");
      }
      console.log(error.message);
    }
    setLoading(false);
  };

  const handleChange = (e) => {
    setState((old) => {
      return {
        ...old,
        [e.target.name]: e.target.value,
      };
    });
  };

  useEffect(() => {
    console.log(formErrors);
    if (Object.keys(formErrors).length === 0 && isSubmit) {
      submitData(state);
    }
  }, [formErrors]);

  const validate = (values) => {
    const errors = {};

    if (!values.email) {
      errors.email = "Email is required!";
    }

    if (!values.password) {
      errors.password = "Password is required!";
    }

    return errors;
  };

  const handleSubmit = () => {
    setFormErrors(validate(state));
    setIsSubmit(true);
  };

  return (
    <>
      <Head>
        <title>GP Admin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_sm.png" />
      </Head>
      <main className="main">
        <div>
          <Navbar />
        </div>
        {loading && <Loader />}
        <div className={styles.loginPage}>
          <div className={styles.loginSec}>
            <div className="main-heading">Login</div>

            <div className={styles.loginInputs}>
              <TextInput
                id="outlined-name"
                label="Email"
                name="email"
                fullWidth={true}
                value={state.email}
                onChange={handleChange}
                error={formErrors.email}
                helperText={formErrors.email}
                // inputProps={{ className: classes.input }}
              />
              <TextInput
                id="outlined-name"
                label="Password"
                name="password"
                fullWidth={true}
                value={state.password}
                onChange={handleChange}
                error={formErrors.password}
                helperText={formErrors.password}
                type="password"
                // inputProps={{ className: classes.input }}
              />
              <PrimaryButton
                onClick={() => {
                  handleSubmit();
                }}
                name="submit"
              />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
