import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import PageNav from "@/components/pageNavigation/PageNav";
import Head from "next/head";

const allProducts = () => {
  return (
    <>
      <Head>
        <title>Graphene Pro - All Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo_sm.png" />
      </Head>
      <main className="main">
        <Navbar />
        <PageNav title="All Products" />
        <Footer />
      </main>
    </>
  );
};

export default allProducts;
